output-format: grouped

# strictness: veryhigh
# doc-warnings: no
# test-warnings: no
max-line-length: 120
# pep8: full

ignore-paths:
  - docs/

mypy:
  run: true
  options:
    ignore-missing-imports: true
    follow-imports: skip
    check-untyped-defs: true
    disallow-any-generics: true
    disallow-untyped-defs: true
    disallow-incomplete-defs: true
    disallow-untyped-decorators: true
    warn-unused-configs: true
    warn-unused-ignores: true
    warn-redundant-casts: true
    extra-checks: true

pylint:
  disable:
    - c-extension-no-member # Needed for mypy
    - too-few-public-methods
    - missing-docstring
    - star-args
    - consider-using-f-string
    - too-many-locals # TODO: clean up these complexity problems
    - too-many-branches
    - too-many-arguments
    - too-many-instance-attributes
    - too-many-function-args
    - too-many-statements
    - too-many-positional-arguments
    - no-else-return

mccabe:
  run: false

pycodestyle:
  disable:
    - E126
    - E501 # line too long

pydocstyle:
  run: false
  disable:
    - D100
    - D101
    - D102
    - D103
    - D107
    - D205
    - D400
    - D401

bandit:
  run: true
  disable:
    - B101 # Use of assert detected.

ruff:
  run: true
  options:
    fix: true
  disable:
    - E501 # line too long
    - S101 # Use of assert detected
    - SIM105 # suppressible-exception (slow code)
